export const UPDATE_FAV_LIST = 'UPDATE_FAV_LIST'
export const ADD_FAV_LIST = 'ADD_FAV_LIST'
export const DEL_FAV_LIST = 'DEL_FAV_LIST'

export const UPDATE_USERNAME = 'UPDATE_USERNAME'
export const UPDATE_AVATAR = 'UPDATE_AVATAR'
