# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-10 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userstat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.TextField()),
                ('user_type', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=-1)),
                ('visitTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='visit time')),
                ('location', models.TextField()),
                ('visit_func', models.TextField()),
                ('visit_param', models.TextField()),
            ],
        ),
    ]
